
// THIS FILE WAS AUTOGENERATED!
// DO NOT MODIFY!

// system includes
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

// local includes
#include "try/v2.0/covariance/Slice.hpp"
#include "definitions.hpp"

// namespace aliases
namespace python = pybind11;

namespace python_v2_0 {
namespace python_covariance {

// Slice wrapper
void wrapSlice(python::module &module)
{
   using namespace try;
   using namespace try::v2_0;

   // type aliases
   using Component = covariance::Slice;

   // create the component
   python::class_<Component> component(
      module,
      "Slice",
      Component::documentation().data()
   );

   // wrap the component
   component
      .def(
         python::init<
            const std::optional<Float64> &,
            const std::optional<Float64> &,
            const std::optional<Float64> &,
            const std::optional<XMLName> &,
            const Integer32 &
         >(),
         python::arg("domain_min") = std::nullopt,
         python::arg("domain_max") = std::nullopt,
         python::arg("domain_value") = std::nullopt,
         python::arg("domain_unit") = std::nullopt,
         python::arg("dimension"),
         Component::documentation("constructor").data()
      )
      .def_property_readonly(
         "domain_min",
         [](const Component &self) { return self.domainMin(); },
         Component::documentation("domain_min").data()
      )
      .def_property_readonly(
         "domain_max",
         [](const Component &self) { return self.domainMax(); },
         Component::documentation("domain_max").data()
      )
      .def_property_readonly(
         "domain_value",
         [](const Component &self) { return self.domainValue(); },
         Component::documentation("domain_value").data()
      )
      .def_property_readonly(
         "domain_unit",
         [](const Component &self) { return self.domainUnit(); },
         Component::documentation("domain_unit").data()
      )
      .def_property_readonly(
         "dimension",
         [](const Component &self) { return self.dimension(); },
         Component::documentation("dimension").data()
      )
   ;

   // add standard component definitions
   addStandardComponentDefinitions< Component >( component );
}

} // namespace python_covariance
} // namespace python_v2_0
