#!/bin/bash

# ------------------------
# Setup
# ------------------------

COMPILE='
   g++
  -std=c++17
  -I../../subprojects/knoop/src
  -I../../subprojects/range-v3-adapter/src/include
  -I../../subprojects/valuable-adapter/src/valuable/include
  -I../../subprojects/pugixml-adapter/src/src
  -I../../subprojects/json-adapter/src/src
  -I../src
  -O3 -Wall -Wextra -Wpedantic '

LIBRARIES=''

# ------------------------
# Compile
# ------------------------

if [ ! -f "pugixml.o" ]; then
$COMPILE ../../subprojects/pugixml-adapter/src/src/pugixml.cpp -c -o pugixml.o
fi

$COMPILE example-00.cpp pugixml.o -o 00 $LIBRARIES
$COMPILE example-01.cpp pugixml.o -o 01 $LIBRARIES
$COMPILE example-02.cpp pugixml.o -o 02 $LIBRARIES
$COMPILE example-03.cpp pugixml.o -o 03 $LIBRARIES
$COMPILE example-04.cpp pugixml.o -o 04 $LIBRARIES
$COMPILE example-05.cpp pugixml.o -o 05 $LIBRARIES
$COMPILE example-06.cpp pugixml.o -o 06 $LIBRARIES
$COMPILE example-07.cpp pugixml.o -o 07 $LIBRARIES
$COMPILE example-08.cpp pugixml.o -o 08 $LIBRARIES
$COMPILE example-09.cpp pugixml.o -o 09 $LIBRARIES
