
!! THIS FILE WAS AUTOGENERATED!
!! DO NOT MODIFY!

module generalElapsedTime
use iso_c_binding
interface


!! -----------------------------------------------------------------------------
!! Basics
!! Create, Assign, Delete
!! -----------------------------------------------------------------------------

!! Create, default, const
function ElapsedTimeDefaultConst() &
      bind(C, name='ElapsedTimeDefaultConst')
   use iso_c_binding
   implicit none
   type(c_ptr) :: ElapsedTimeDefaultConst
end function ElapsedTimeDefaultConst

!! Create, default
function ElapsedTimeDefault() &
      bind(C, name='ElapsedTimeDefault')
   use iso_c_binding
   implicit none
   type(c_ptr) :: ElapsedTimeDefault
end function ElapsedTimeDefault

!! Create, general, const
function ElapsedTimeCreateConst( &
   label, &
   time, &
   yields, &
   incidentEnergies, &
   labelSize &
) &
      bind(C, name='ElapsedTimeCreateConst')
   use iso_c_binding
   implicit none
   integer(c_size_t), intent(in), value :: labelSize
   character(c_char), intent(in) :: label(labelSize)
   type(c_ptr), value :: time
   type(c_ptr), value :: yields
   type(c_ptr), value :: incidentEnergies
   type(c_ptr) :: ElapsedTimeCreateConst
end function ElapsedTimeCreateConst

!! Create, general
function ElapsedTimeCreate( &
   label, &
   time, &
   yields, &
   incidentEnergies, &
   labelSize &
) &
      bind(C, name='ElapsedTimeCreate')
   use iso_c_binding
   implicit none
   integer(c_size_t), intent(in), value :: labelSize
   character(c_char), intent(in) :: label(labelSize)
   type(c_ptr), value :: time
   type(c_ptr), value :: yields
   type(c_ptr), value :: incidentEnergies
   type(c_ptr) :: ElapsedTimeCreate
end function ElapsedTimeCreate

!! Assign
subroutine ElapsedTimeAssign(handleLHS, handleRHS) &
      bind(C, name='ElapsedTimeAssign')
   use iso_c_binding
   implicit none
   type(c_ptr), value :: handleLHS, handleRHS
end subroutine ElapsedTimeAssign

!! Delete
subroutine ElapsedTimeDelete(handle) &
      bind(C, name='ElapsedTimeDelete')
   use iso_c_binding
   implicit none
   type(c_ptr), value :: handle
end subroutine ElapsedTimeDelete


!! -----------------------------------------------------------------------------
!! I/O
!! Read, Write, Print
!! Each returns 0 if failure, 1 if success.
!! -----------------------------------------------------------------------------

!! Read from file
function ElapsedTimeRead(handle, filename, filenameSize) &
      bind(C, name='ElapsedTimeRead')
   use iso_c_binding
   implicit none
   type(c_ptr), value :: handle
   integer(c_size_t), value :: filenameSize
   character(c_char), intent(in) :: filename(filenameSize)
   integer(c_int) :: ElapsedTimeRead
end function ElapsedTimeRead

!! Write to file
function ElapsedTimeWrite(handle, filename, filenameSize) &
      bind(C, name='ElapsedTimeWrite')
   use iso_c_binding
   implicit none
   type(c_ptr), intent(in), value :: handle
   integer(c_size_t), value :: filenameSize
   character(c_char), intent(in) :: filename(filenameSize)
   integer(c_int) :: ElapsedTimeWrite
end function ElapsedTimeWrite

!! Print to standard output, in our prettyprinting format
function ElapsedTimePrint(handle) &
      bind(C, name='ElapsedTimePrint')
   use iso_c_binding
   implicit none
   type(c_ptr), intent(in), value :: handle
   integer(c_int) :: ElapsedTimePrint
end function ElapsedTimePrint

!! Print to standard output, as XML
function ElapsedTimePrintXML(handle) &
      bind(C, name='ElapsedTimePrintXML')
   use iso_c_binding
   implicit none
   type(c_ptr), intent(in), value :: handle
   integer(c_int) :: ElapsedTimePrintXML
end function ElapsedTimePrintXML

!! Print to standard output, as JSON
function ElapsedTimePrintJSON(handle) &
      bind(C, name='ElapsedTimePrintJSON')
   use iso_c_binding
   implicit none
   type(c_ptr), intent(in), value :: handle
   integer(c_int) :: ElapsedTimePrintJSON
end function ElapsedTimePrintJSON


!! -----------------------------------------------------------------------------
!! Metadatum: label
!! -----------------------------------------------------------------------------

!! Has
function ElapsedTimeLabelHas(handle) &
      bind(C, name='ElapsedTimeLabelHas')
   use iso_c_binding
   implicit none
   type(c_ptr), intent(in), value :: handle
   integer(c_int) :: ElapsedTimeLabelHas
end function ElapsedTimeLabelHas

!! Get
function ElapsedTimeLabelGet(handle) &
      bind(C, name='ElapsedTimeLabelGet')
   use iso_c_binding
   implicit none
   type(c_ptr), intent(in), value :: handle
   type(c_ptr) :: ElapsedTimeLabelGet
end function ElapsedTimeLabelGet

!! Set
subroutine ElapsedTimeLabelSet(handle, label, labelSize) &
      bind(C, name='ElapsedTimeLabelSet')
   use iso_c_binding
   implicit none
   type(c_ptr), value :: handle
   integer(c_size_t), intent(in), value :: labelSize
   character(c_char), intent(in) :: label(labelSize)
end subroutine ElapsedTimeLabelSet


!! -----------------------------------------------------------------------------
!! Child: time
!! -----------------------------------------------------------------------------

!! Has
function ElapsedTimeTimeHas(handle) &
      bind(C, name='ElapsedTimeTimeHas')
   use iso_c_binding
   implicit none
   type(c_ptr), intent(in), value :: handle
   integer(c_int) :: ElapsedTimeTimeHas
end function ElapsedTimeTimeHas

!! Get, const
function ElapsedTimeTimeGetConst(handle) &
      bind(C, name='ElapsedTimeTimeGetConst')
   use iso_c_binding
   implicit none
   type(c_ptr), intent(in), value :: handle
   type(c_ptr) :: ElapsedTimeTimeGetConst
end function ElapsedTimeTimeGetConst

!! Get
function ElapsedTimeTimeGet(handle) &
      bind(C, name='ElapsedTimeTimeGet')
   use iso_c_binding
   implicit none
   type(c_ptr), intent(in), value :: handle
   type(c_ptr) :: ElapsedTimeTimeGet
end function ElapsedTimeTimeGet

!! Set
subroutine ElapsedTimeTimeSet(handle, fieldHandle) &
      bind(C, name='ElapsedTimeTimeSet')
   use iso_c_binding
   implicit none
   type(c_ptr), value :: handle
   type(c_ptr), value :: fieldHandle
end subroutine ElapsedTimeTimeSet


!! -----------------------------------------------------------------------------
!! Child: yields
!! -----------------------------------------------------------------------------

!! Has
function ElapsedTimeYieldsHas(handle) &
      bind(C, name='ElapsedTimeYieldsHas')
   use iso_c_binding
   implicit none
   type(c_ptr), intent(in), value :: handle
   integer(c_int) :: ElapsedTimeYieldsHas
end function ElapsedTimeYieldsHas

!! Get, const
function ElapsedTimeYieldsGetConst(handle) &
      bind(C, name='ElapsedTimeYieldsGetConst')
   use iso_c_binding
   implicit none
   type(c_ptr), intent(in), value :: handle
   type(c_ptr) :: ElapsedTimeYieldsGetConst
end function ElapsedTimeYieldsGetConst

!! Get
function ElapsedTimeYieldsGet(handle) &
      bind(C, name='ElapsedTimeYieldsGet')
   use iso_c_binding
   implicit none
   type(c_ptr), intent(in), value :: handle
   type(c_ptr) :: ElapsedTimeYieldsGet
end function ElapsedTimeYieldsGet

!! Set
subroutine ElapsedTimeYieldsSet(handle, fieldHandle) &
      bind(C, name='ElapsedTimeYieldsSet')
   use iso_c_binding
   implicit none
   type(c_ptr), value :: handle
   type(c_ptr), value :: fieldHandle
end subroutine ElapsedTimeYieldsSet


!! -----------------------------------------------------------------------------
!! Child: incidentEnergies
!! -----------------------------------------------------------------------------

!! Has
function ElapsedTimeIncidentEnergiesHas(handle) &
      bind(C, name='ElapsedTimeIncidentEnergiesHas')
   use iso_c_binding
   implicit none
   type(c_ptr), intent(in), value :: handle
   integer(c_int) :: ElapsedTimeIncidentEnergiesHas
end function ElapsedTimeIncidentEnergiesHas

!! Get, const
function ElapsedTimeIncidentEnergiesGetConst(handle) &
      bind(C, name='ElapsedTimeIncidentEnergiesGetConst')
   use iso_c_binding
   implicit none
   type(c_ptr), intent(in), value :: handle
   type(c_ptr) :: ElapsedTimeIncidentEnergiesGetConst
end function ElapsedTimeIncidentEnergiesGetConst

!! Get
function ElapsedTimeIncidentEnergiesGet(handle) &
      bind(C, name='ElapsedTimeIncidentEnergiesGet')
   use iso_c_binding
   implicit none
   type(c_ptr), intent(in), value :: handle
   type(c_ptr) :: ElapsedTimeIncidentEnergiesGet
end function ElapsedTimeIncidentEnergiesGet

!! Set
subroutine ElapsedTimeIncidentEnergiesSet(handle, fieldHandle) &
      bind(C, name='ElapsedTimeIncidentEnergiesSet')
   use iso_c_binding
   implicit none
   type(c_ptr), value :: handle
   type(c_ptr), value :: fieldHandle
end subroutine ElapsedTimeIncidentEnergiesSet


!! -----------------------------------------------------------------------------
!! -----------------------------------------------------------------------------

end interface
end module generalElapsedTime
