
// THIS FILE WAS AUTOGENERATED!
// DO NOT MODIFY!

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

// v2.0 interface
namespace python_v2_0 {

// styles declarations
namespace python_styles {
   void wrapProjectileEnergyDomain(py::module &);
   void wrapTemperature(py::module &);
   void wrapEvaluated(py::module &);
   void wrapCrossSectionReconstructed(py::module &);
   void wrapAngularDistributionReconstructed(py::module &);
   void wrapCoulombPlusNuclearElasticMuCutoff(py::module &);
   void wrapHeated(py::module &);
   void wrapAverageProductData(py::module &);
   void wrapMonteCarlo_cdf(py::module &);
   void wrapGriddedCrossSection(py::module &);
   void wrapURR_probabilityTables(py::module &);
   void wrapMultiGroup(py::module &);
   void wrapTransportable(py::module &);
   void wrapTransportables(py::module &);
   void wrapFlux(py::module &);
   void wrapInverseSpeed(py::module &);
   void wrapHeatedMultiGroup(py::module &);
   void wrapSnElasticUpScatter(py::module &);
   void wrapStyles(py::module &);
   void wrapSigmaZeros(py::module &);
   void wrapBondarenko(py::module &);
   void wrapMultiBand(py::module &);
   void wrapEqualProbableBins(py::module &);
   void wrapRealization(py::module &);
} // namespace python_styles

// wrapper for styles
void wrapStyles(py::module &module)
{
   // create the styles submodule
   py::module submodule = module.def_submodule(
      "styles",
      "test v2.0 styles"
   );

   // wrap styles components
   python_styles::wrapProjectileEnergyDomain(submodule);
   python_styles::wrapTemperature(submodule);
   python_styles::wrapEvaluated(submodule);
   python_styles::wrapCrossSectionReconstructed(submodule);
   python_styles::wrapAngularDistributionReconstructed(submodule);
   python_styles::wrapCoulombPlusNuclearElasticMuCutoff(submodule);
   python_styles::wrapHeated(submodule);
   python_styles::wrapAverageProductData(submodule);
   python_styles::wrapMonteCarlo_cdf(submodule);
   python_styles::wrapGriddedCrossSection(submodule);
   python_styles::wrapURR_probabilityTables(submodule);
   python_styles::wrapMultiGroup(submodule);
   python_styles::wrapTransportable(submodule);
   python_styles::wrapTransportables(submodule);
   python_styles::wrapFlux(submodule);
   python_styles::wrapInverseSpeed(submodule);
   python_styles::wrapHeatedMultiGroup(submodule);
   python_styles::wrapSnElasticUpScatter(submodule);
   python_styles::wrapStyles(submodule);
   python_styles::wrapSigmaZeros(submodule);
   python_styles::wrapBondarenko(submodule);
   python_styles::wrapMultiBand(submodule);
   python_styles::wrapEqualProbableBins(submodule);
   python_styles::wrapRealization(submodule);
};

} // namespace python_v2_0
