
// THIS FILE WAS AUTOGENERATED!
// DO NOT MODIFY!

#include "test/v2_0/containers/XYs2d.hpp"
#include "XYs2d.h"

using namespace njoy::GNDStk;
using namespace test::v2_0;

using C = XYs2dClass;
using CPP = multigroup::XYs2d;

static const std::string CLASSNAME = "XYs2d";

namespace extract {
   static auto index = [](auto &obj) { return &obj.index; };
   static auto interpolation = [](auto &obj) { return &obj.interpolation; };
   static auto interpolationQualifier = [](auto &obj) { return &obj.interpolationQualifier; };
   static auto outerDomainValue = [](auto &obj) { return &obj.outerDomainValue; };
   static auto axes = [](auto &obj) { return &obj.axes; };
   static auto function1ds = [](auto &obj) { return &obj.function1ds; };
   static auto uncertainty = [](auto &obj) { return &obj.uncertainty; };
}

using CPPAxes = containers::Axes;
using CPPFunction1ds = containers::Function1ds;
using CPPUncertainty = containers::Uncertainty;


// -----------------------------------------------------------------------------
// Basics
// Create, Assign, Delete
// -----------------------------------------------------------------------------

// Create, default, const
Handle2ConstXYs2d
XYs2dDefaultConst()
{
   return detail::createHandle<CPP,C>
      (CLASSNAME, CLASSNAME+"DefaultConst");
}

// Create, default
Handle2XYs2d
XYs2dDefault()
{
   return detail::createHandle<CPP,C>
      (CLASSNAME, CLASSNAME+"Default");
}

// Create, general, const
Handle2ConstXYs2d
XYs2dCreateConst(
   const Integer32 index,
   const enums::Interpolation interpolation,
   const XMLName interpolationQualifier,
   const Float64 outerDomainValue,
   ConstHandle2ConstAxes axes,
   ConstHandle2ConstFunction1ds function1ds,
   ConstHandle2ConstUncertainty uncertainty
) {
   ConstHandle2XYs2d handle = detail::createHandle<CPP,C>(
      CLASSNAME, CLASSNAME+"CreateConst",
      index,
      interpolation,
      interpolationQualifier,
      outerDomainValue,
      detail::tocpp<CPPAxes>(axes),
      detail::tocpp<CPPFunction1ds>(function1ds),
      detail::tocpp<CPPUncertainty>(uncertainty)
   );
   return handle;
}

// Create, general
Handle2XYs2d
XYs2dCreate(
   const Integer32 index,
   const enums::Interpolation interpolation,
   const XMLName interpolationQualifier,
   const Float64 outerDomainValue,
   ConstHandle2ConstAxes axes,
   ConstHandle2ConstFunction1ds function1ds,
   ConstHandle2ConstUncertainty uncertainty
) {
   ConstHandle2XYs2d handle = detail::createHandle<CPP,C>(
      CLASSNAME, CLASSNAME+"Create",
      index,
      interpolation,
      interpolationQualifier,
      outerDomainValue,
      detail::tocpp<CPPAxes>(axes),
      detail::tocpp<CPPFunction1ds>(function1ds),
      detail::tocpp<CPPUncertainty>(uncertainty)
   );
   return handle;
}

// Assign
// Use this to assign one handled object to another. Don't assign handles,
// as with to = from. That has a meaning that you probably don't intend.
void
XYs2dAssign(ConstHandle2XYs2d self, ConstHandle2ConstXYs2d from)
{
   detail::assignHandle<CPP,C>
      (CLASSNAME, CLASSNAME+"Assign", self, from);
}

// Delete
// We'll attempt to remove no-longer-used objects automatically, but you
// may improve performance if you delete them when you're done with them.
void
XYs2dDelete(ConstHandle2ConstXYs2d self)
{
   detail::deleteHandle<CPP,C>
      (CLASSNAME, CLASSNAME+"Delete", self);
}


// -----------------------------------------------------------------------------
// I/O
// Read, Write, Print
// Each returns 0 if failure, 1 if success.
// -----------------------------------------------------------------------------

// Read from file
// File can be XML, JSON, or HDF5.
// We'll examine the file's contents to determine its type automatically.
int
XYs2dRead(ConstHandle2XYs2d self, const char *const filename)
{
   return detail::readHandle<CPP,C>
      (CLASSNAME, CLASSNAME+"Read", self, filename);
}

// Write to file
// File can be XML, JSON, or HDF5.
// We'll use filename's extension to determine the type you want written.
int
XYs2dWrite(ConstHandle2ConstXYs2d self, const char *const filename)
{
   return detail::writeHandle<CPP,C>
      (CLASSNAME, CLASSNAME+"Write", self, filename);
}

// Print to standard output, in our prettyprinting format
int
XYs2dPrint(ConstHandle2ConstXYs2d self)
{
   return detail::printHandle<CPP,C>
      (CLASSNAME, CLASSNAME+"Print", self);
}

// Print to standard output, as XML
int
XYs2dPrintXML(ConstHandle2ConstXYs2d self)
{
   return detail::printHandle<CPP,C>
      (CLASSNAME, CLASSNAME+"PrintXML", self, "XML");
}

// Print to standard output, as JSON
int
XYs2dPrintJSON(ConstHandle2ConstXYs2d self)
{
   return detail::printHandle<CPP,C>
      (CLASSNAME, CLASSNAME+"PrintJSON", self, "JSON");
}


// -----------------------------------------------------------------------------
// Metadatum: index
// -----------------------------------------------------------------------------

// Has
int
XYs2dIndexHas(ConstHandle2ConstXYs2d self)
{
   return detail::hasField<CPP>
      (CLASSNAME, CLASSNAME+"IndexHas", self, extract::index);
}

// Get
// Returns by value
Integer32
XYs2dIndexGet(ConstHandle2ConstXYs2d self)
{
   return detail::getField<CPP>
      (CLASSNAME, CLASSNAME+"IndexGet", self, extract::index);
}

// Set
void
XYs2dIndexSet(ConstHandle2XYs2d self, const Integer32 index)
{
   detail::setField<CPP>
      (CLASSNAME, CLASSNAME+"IndexSet", self, extract::index, index);
}


// -----------------------------------------------------------------------------
// Metadatum: interpolation
// -----------------------------------------------------------------------------

// Has
int
XYs2dInterpolationHas(ConstHandle2ConstXYs2d self)
{
   return detail::hasField<CPP>
      (CLASSNAME, CLASSNAME+"InterpolationHas", self, extract::interpolation);
}

// Get
// Returns by value
enums::Interpolation
XYs2dInterpolationGet(ConstHandle2ConstXYs2d self)
{
   return detail::getField<CPP>
      (CLASSNAME, CLASSNAME+"InterpolationGet", self, extract::interpolation);
}

// Set
void
XYs2dInterpolationSet(ConstHandle2XYs2d self, const enums::Interpolation interpolation)
{
   detail::setField<CPP>
      (CLASSNAME, CLASSNAME+"InterpolationSet", self, extract::interpolation, interpolation);
}


// -----------------------------------------------------------------------------
// Metadatum: interpolationQualifier
// -----------------------------------------------------------------------------

// Has
int
XYs2dInterpolationQualifierHas(ConstHandle2ConstXYs2d self)
{
   return detail::hasField<CPP>
      (CLASSNAME, CLASSNAME+"InterpolationQualifierHas", self, extract::interpolationQualifier);
}

// Get
// Returns by value
XMLName
XYs2dInterpolationQualifierGet(ConstHandle2ConstXYs2d self)
{
   return detail::getField<CPP>
      (CLASSNAME, CLASSNAME+"InterpolationQualifierGet", self, extract::interpolationQualifier);
}

// Set
void
XYs2dInterpolationQualifierSet(ConstHandle2XYs2d self, const XMLName interpolationQualifier)
{
   detail::setField<CPP>
      (CLASSNAME, CLASSNAME+"InterpolationQualifierSet", self, extract::interpolationQualifier, interpolationQualifier);
}


// -----------------------------------------------------------------------------
// Metadatum: outerDomainValue
// -----------------------------------------------------------------------------

// Has
int
XYs2dOuterDomainValueHas(ConstHandle2ConstXYs2d self)
{
   return detail::hasField<CPP>
      (CLASSNAME, CLASSNAME+"OuterDomainValueHas", self, extract::outerDomainValue);
}

// Get
// Returns by value
Float64
XYs2dOuterDomainValueGet(ConstHandle2ConstXYs2d self)
{
   return detail::getField<CPP>
      (CLASSNAME, CLASSNAME+"OuterDomainValueGet", self, extract::outerDomainValue);
}

// Set
void
XYs2dOuterDomainValueSet(ConstHandle2XYs2d self, const Float64 outerDomainValue)
{
   detail::setField<CPP>
      (CLASSNAME, CLASSNAME+"OuterDomainValueSet", self, extract::outerDomainValue, outerDomainValue);
}


// -----------------------------------------------------------------------------
// Child: axes
// -----------------------------------------------------------------------------

// Has
int
XYs2dAxesHas(ConstHandle2ConstXYs2d self)
{
   return detail::hasField<CPP>
      (CLASSNAME, CLASSNAME+"AxesHas", self, extract::axes);
}

// Get, const
Handle2ConstAxes
XYs2dAxesGetConst(ConstHandle2ConstXYs2d self)
{
   return detail::getField<CPP,Handle2ConstAxes>
      (CLASSNAME, CLASSNAME+"AxesGetConst", self, extract::axes);
}

// Get, non-const
Handle2Axes
XYs2dAxesGet(ConstHandle2XYs2d self)
{
   return detail::getField<CPP,Handle2Axes>
      (CLASSNAME, CLASSNAME+"AxesGet", self, extract::axes);
}

// Set
void
XYs2dAxesSet(ConstHandle2XYs2d self, ConstHandle2ConstAxes axes)
{
   detail::setField<CPP,CPPAxes>
      (CLASSNAME, CLASSNAME+"AxesSet", self, extract::axes, axes);
}


// -----------------------------------------------------------------------------
// Child: function1ds
// -----------------------------------------------------------------------------

// Has
int
XYs2dFunction1dsHas(ConstHandle2ConstXYs2d self)
{
   return detail::hasField<CPP>
      (CLASSNAME, CLASSNAME+"Function1dsHas", self, extract::function1ds);
}

// Get, const
Handle2ConstFunction1ds
XYs2dFunction1dsGetConst(ConstHandle2ConstXYs2d self)
{
   return detail::getField<CPP,Handle2ConstFunction1ds>
      (CLASSNAME, CLASSNAME+"Function1dsGetConst", self, extract::function1ds);
}

// Get, non-const
Handle2Function1ds
XYs2dFunction1dsGet(ConstHandle2XYs2d self)
{
   return detail::getField<CPP,Handle2Function1ds>
      (CLASSNAME, CLASSNAME+"Function1dsGet", self, extract::function1ds);
}

// Set
void
XYs2dFunction1dsSet(ConstHandle2XYs2d self, ConstHandle2ConstFunction1ds function1ds)
{
   detail::setField<CPP,CPPFunction1ds>
      (CLASSNAME, CLASSNAME+"Function1dsSet", self, extract::function1ds, function1ds);
}


// -----------------------------------------------------------------------------
// Child: uncertainty
// -----------------------------------------------------------------------------

// Has
int
XYs2dUncertaintyHas(ConstHandle2ConstXYs2d self)
{
   return detail::hasField<CPP>
      (CLASSNAME, CLASSNAME+"UncertaintyHas", self, extract::uncertainty);
}

// Get, const
Handle2ConstUncertainty
XYs2dUncertaintyGetConst(ConstHandle2ConstXYs2d self)
{
   return detail::getField<CPP,Handle2ConstUncertainty>
      (CLASSNAME, CLASSNAME+"UncertaintyGetConst", self, extract::uncertainty);
}

// Get, non-const
Handle2Uncertainty
XYs2dUncertaintyGet(ConstHandle2XYs2d self)
{
   return detail::getField<CPP,Handle2Uncertainty>
      (CLASSNAME, CLASSNAME+"UncertaintyGet", self, extract::uncertainty);
}

// Set
void
XYs2dUncertaintySet(ConstHandle2XYs2d self, ConstHandle2ConstUncertainty uncertainty)
{
   detail::setField<CPP,CPPUncertainty>
      (CLASSNAME, CLASSNAME+"UncertaintySet", self, extract::uncertainty, uncertainty);
}


// -----------------------------------------------------------------------------
// Custom functionality
// -----------------------------------------------------------------------------

#include "v2.0/containers/XYs2d/src/custom.cpp"
