
// THIS FILE WAS AUTOGENERATED!
// DO NOT MODIFY!

#ifndef TEST_V2_0_STYLES_ANGULARDISTRIBUTIONRECONSTRUCTED
#define TEST_V2_0_STYLES_ANGULARDISTRIBUTIONRECONSTRUCTED

#include "test/v2.0/styles/Temperature.hpp"
#include "test/v2.0/documentation/Documentation.hpp"

namespace test {
namespace v2_0 {
namespace styles {

// -----------------------------------------------------------------------------
// styles::
// class AngularDistributionReconstructed
// -----------------------------------------------------------------------------

class AngularDistributionReconstructed :
   public Component<styles::AngularDistributionReconstructed>
{
   friend class Component;

   // ------------------------
   // For Component
   // ------------------------

   // Names: this namespace and class, and original nodes (as in XML <...>)
   static auto NAMESPACE() { return "styles"; }
   static auto CLASS() { return "AngularDistributionReconstructed"; }
   static auto NODENAME() { return "angularDistributionReconstructed"; }

   // Core Interface multi-query to transfer information to/from core Nodes
   static auto KEYS()
   {
      return
         // comment
         ++Child<std::string>(special::comment) / CommentConverter{} |

         // metadata
         std::string{}
            / Meta<>("date") |
         XMLName{}
            / Meta<>("label") |
         std::optional<XMLName>{}
            / Meta<>("derivedFrom") |

         // children
         --Child<std::optional<styles::Temperature>>
            ("temperature") |
         --Child<std::optional<documentation::Documentation>>
            ("documentation")
      ;
   }

   // Data member names. Usually - but not necessarily - the same as the node
   // names appearing in KEYS(). These are used by Component's prettyprinter.
   static const auto &FIELDNAMES()
   {
      static const std::vector<std::string> names = {
         "comment",
         "date",
         "label",
         "derivedFrom",
         "temperature",
         "documentation"
      };
      return names;
   }

   // Data member names, as they'll be presented in the Python bindings.
   static const auto &PYTHONNAMES()
   {
      static const std::vector<std::string> names = {
         "comment",
         "date",
         "label",
         "derived_from",
         "temperature",
         "documentation"
      };
      return names;
   }

   // ------------------------
   // Public interface
   // ------------------------

public:

   using component_t = Component;
   using Component::construct;

   // ------------------------
   // Data members
   // ------------------------

   // comment
   Field<std::vector<std::string>> comment{this};

   // metadata
   Field<std::string>
      date{this};
   Field<XMLName>
      label{this};
   Field<std::optional<XMLName>>
      derivedFrom{this};

   // children
   Field<std::optional<styles::Temperature>>
      temperature{this};
   Field<std::optional<documentation::Documentation>>
      documentation{this};

   // ------------------------
   // Constructors
   // ------------------------

   #define GNDSTK_COMPONENT(blockdata) \
   Component( \
      blockdata, \
      this->comment, \
      this->date, \
      this->label, \
      this->derivedFrom, \
      this->temperature, \
      this->documentation \
   )

   // default
   AngularDistributionReconstructed() :
      GNDSTK_COMPONENT(BlockData{})
   {
      Component::finish();
   }

   // from fields, comment excluded
   explicit AngularDistributionReconstructed(
      const wrapper<std::string>
         &date,
      const wrapper<XMLName>
         &label = {},
      const wrapper<std::optional<XMLName>>
         &derivedFrom = {},
      const wrapper<std::optional<styles::Temperature>>
         &temperature = {},
      const wrapper<std::optional<documentation::Documentation>>
         &documentation = {}
   ) :
      GNDSTK_COMPONENT(BlockData{}),
      date(this,date),
      label(this,label),
      derivedFrom(this,derivedFrom),
      temperature(this,temperature),
      documentation(this,documentation)
   {
      Component::finish();
   }

   // from node
   explicit AngularDistributionReconstructed(const Node &node) :
      GNDSTK_COMPONENT(BlockData{})
   {
      Component::finish(node);
   }

   // copy
   AngularDistributionReconstructed(const AngularDistributionReconstructed &other) :
      GNDSTK_COMPONENT(other.baseBlockData()),
      comment(this,other.comment),
      date(this,other.date),
      label(this,other.label),
      derivedFrom(this,other.derivedFrom),
      temperature(this,other.temperature),
      documentation(this,other.documentation)
   {
      Component::finish(other);
   }

   // move
   AngularDistributionReconstructed(AngularDistributionReconstructed &&other) :
      GNDSTK_COMPONENT(other.baseBlockData()),
      comment(this,std::move(other.comment)),
      date(this,std::move(other.date)),
      label(this,std::move(other.label)),
      derivedFrom(this,std::move(other.derivedFrom)),
      temperature(this,std::move(other.temperature)),
      documentation(this,std::move(other.documentation))
   {
      Component::finish(other);
   }

   // ------------------------
   // Assignment operators
   // ------------------------

   // copy
   AngularDistributionReconstructed &operator=(const AngularDistributionReconstructed &other)
   {
      if (this != &other) {
         Component::operator=(other);
         comment = other.comment;
         date = other.date;
         label = other.label;
         derivedFrom = other.derivedFrom;
         temperature = other.temperature;
         documentation = other.documentation;
      }
      return *this;
   }

   // move
   AngularDistributionReconstructed &operator=(AngularDistributionReconstructed &&other)
   {
      if (this != &other) {
         Component::operator=(std::move(other));
         comment = std::move(other.comment);
         date = std::move(other.date);
         label = std::move(other.label);
         derivedFrom = std::move(other.derivedFrom);
         temperature = std::move(other.temperature);
         documentation = std::move(other.documentation);
      }
      return *this;
   }

   // ------------------------
   // Custom functionality
   // ------------------------

   #include "test/v2.0/styles/AngularDistributionReconstructed/src/custom.hpp"
   #undef GNDSTK_COMPONENT
}; // class AngularDistributionReconstructed

} // namespace styles
} // namespace v2_0
} // namespace test

#endif
