
// THIS FILE WAS AUTOGENERATED!
// DO NOT MODIFY!

#ifndef TEST_V2_0_STYLES_BONDARENKO
#define TEST_V2_0_STYLES_BONDARENKO

#include "test/v2.0/styles/SigmaZeros.hpp"
#include "test/v2.0/documentation/Documentation.hpp"

namespace test {
namespace v2_0 {
namespace styles {

// -----------------------------------------------------------------------------
// styles::
// class Bondarenko
// -----------------------------------------------------------------------------

class Bondarenko : public Component<styles::Bondarenko> {
   friend class Component;

   // ------------------------
   // For Component
   // ------------------------

   // Names: this namespace, this class, a field/node of this type
   static auto NAMESPACE() { return "styles"; }
   static auto CLASS() { return "Bondarenko"; }
   static auto FIELD() { return "Bondarenko"; }

   // Core Interface multi-query to extract metadata and child nodes
   static auto KEYS()
   {
      return
         // metadata
         std::string{}
            / Meta<>("date") |
         XMLName{}
            / Meta<>("derivedFrom") |
         XMLName{}
            / Meta<>("label") |
         // children
         --Child<styles::SigmaZeros>("sigmaZeros") |
         --Child<std::optional<documentation::Documentation>>("documentation")
      ;
   }

public:
   using Component::construct;

   // metadata
   Field<std::string> date{this};
   Field<XMLName> derivedFrom{this};
   Field<XMLName> label{this};

   // children
   Field<styles::SigmaZeros> sigmaZeros{this};
   Field<std::optional<documentation::Documentation>> documentation{this};

   // ------------------------
   // Constructors
   // ------------------------

   #define GNDSTK_COMPONENT(blockdata) Component(blockdata, \
      this->date, \
      this->derivedFrom, \
      this->label, \
      this->sigmaZeros, \
      this->documentation)

   // default
   Bondarenko() :
      GNDSTK_COMPONENT(BlockData{})
   {
      Component::finish();
   }

   // from fields
   explicit Bondarenko(
      const wrapper<std::string> &date,
      const wrapper<XMLName> &derivedFrom = {},
      const wrapper<XMLName> &label = {},
      const wrapper<styles::SigmaZeros> &sigmaZeros = {},
      const wrapper<std::optional<documentation::Documentation>> &documentation = {}
   ) :
      GNDSTK_COMPONENT(BlockData{}),
      date(this,date),
      derivedFrom(this,derivedFrom),
      label(this,label),
      sigmaZeros(this,sigmaZeros),
      documentation(this,documentation)
   {
      Component::finish();
   }

   // from node
   explicit Bondarenko(const Node &node) :
      GNDSTK_COMPONENT(BlockData{})
   {
      Component::finish(node);
   }

   // copy
   Bondarenko(const Bondarenko &other) :
      GNDSTK_COMPONENT(other.baseBlockData()),
      date(this,other.date),
      derivedFrom(this,other.derivedFrom),
      label(this,other.label),
      sigmaZeros(this,other.sigmaZeros),
      documentation(this,other.documentation)
   {
      Component::finish(other);
   }

   // move
   Bondarenko(Bondarenko &&other) :
      GNDSTK_COMPONENT(other.baseBlockData()),
      date(this,std::move(other.date)),
      derivedFrom(this,std::move(other.derivedFrom)),
      label(this,std::move(other.label)),
      sigmaZeros(this,std::move(other.sigmaZeros)),
      documentation(this,std::move(other.documentation))
   {
      Component::finish(other);
   }

   // ------------------------
   // Assignment operators
   // ------------------------

   Bondarenko &operator=(const Bondarenko &) = default;
   Bondarenko &operator=(Bondarenko &&) = default;

   // ------------------------
   // Custom functionality
   // ------------------------

   #include "test/v2.0/styles/Bondarenko/src/custom.hpp"
   #undef GNDSTK_COMPONENT
}; // class Bondarenko

} // namespace styles
} // namespace v2_0
} // namespace test

#endif
