
// THIS FILE WAS AUTOGENERATED!
// DO NOT MODIFY!

#ifndef NJOY_GNDSTK_V2_0_TRANSPORT_PRODUCTIONS
#define NJOY_GNDSTK_V2_0_TRANSPORT_PRODUCTIONS

// core interface
#include "GNDStk.hpp"

// v2.0 dependencies
#include "GNDStk/v2.0/transport/Production.hpp"

namespace njoy {
namespace GNDStk {
namespace v2_0 {

using namespace njoy::GNDStk::core;



// -----------------------------------------------------------------------------
// transport::
// class Productions
// -----------------------------------------------------------------------------

namespace transport {

class Productions : public Component<Productions> {


   // ------------------------
   // For Component
   // ------------------------

   friend class Component;

   // Current namespace, current class, and GNDS node name
   static auto namespaceName() { return "transport"; }
   static auto className() { return "Productions"; }
   static auto GNDSName() { return "productions"; }

   // Core Interface multi-query to extract metadata and child nodes
   static auto keys()
   {
      return
         // children
         std::optional<transport::Production>{}
            / --Child<>("production")
      ;
   }

public:

   using Component::construct;

   // ------------------------
   // Relevant defaults
   // FYI for users
   // ------------------------

   static inline const struct Defaults {
   } defaults;

   // ------------------------
   // Raw GNDS content
   // ------------------------

   struct {
      // children
      std::optional<transport::Production> production;
   } content;

   // ------------------------
   // Getters
   // const and non-const
   // ------------------------

   // production
   const std::optional<transport::Production> &production() const
      { return content.production; }
   std::optional<transport::Production> &production()
      { return content.production; }

   // ------------------------
   // Setters
   // non-const
   // All return *this
   // ------------------------

   // production(value)
   Productions &production(const std::optional<transport::Production> &obj)
      { production() = obj; return *this; }

   // ------------------------
   // Construction
   // ------------------------

   // default
   Productions() :
      Component{
         BodyText{},
         content.production
      }
   {
      Component::finish();
   }

   // copy
   Productions(const Productions &other) :
      Component{
         other,
         content.production
      },
      content{other.content}
   {
      Component::finish(other);
   }

   // move
   Productions(Productions &&other) :
      Component{
         other,
         content.production
      },
      content{std::move(other.content)}
   {
      Component::finish(other);
   }

   // from node
   Productions(const Node &node) :
      Component{
         BodyText{},
         content.production
      }
   {
      Component::finish(node);
   }

   // from fields
   explicit Productions(
      const std::optional<transport::Production> &production
   ) :
      Component{
         BodyText{},
         content.production
      },
      content{
         production
      }
   {
      Component::finish();
   }

   // ------------------------
   // Assignment
   // ------------------------

   // copy
   Productions &operator=(const Productions &) = default;

   // move
   Productions &operator=(Productions &&) = default;

   // ------------------------
   // Custom functionality
   // ------------------------

   #include "GNDStk/v2.0/transport/Productions/src/custom.hpp"

}; // class Productions

} // namespace transport
} // namespace v2_0
} // namespace GNDStk
} // namespace njoy

#endif
