
// THIS FILE WAS AUTOGENERATED!
// DO NOT MODIFY!

// system includes
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

// local includes
#include "test/v2.0/transport/MultiplicitySums.hpp"
#include "definitions.hpp"

// namespace aliases
namespace py = pybind11;

namespace python_v2_0 {
namespace python_transport {

// wrapper for transport::MultiplicitySums
void wrapMultiplicitySums(py::module &module)
{
   using namespace test;
   using namespace test::v2_0;

   // type aliases
   using cppCLASS = transport::MultiplicitySums;

   // create the Python object
   py::class_<cppCLASS> object(
      module, "MultiplicitySums",
      cppCLASS::component_t::documentation().data()
   );

   // constructor: from fields
   object.def(
      py::init<
         const std::optional<std::vector<transport::MultiplicitySum>> &
      >(),
      py::arg("multiplicity_sum") = std::nullopt,
      cppCLASS::component_t::documentation("constructor").data()
   );

   // get/set multiplicitySum
   object.def_property(
      "multiplicity_sum",
      [](const cppCLASS &self) -> decltype(auto)
      {
         return self.multiplicitySum();
      },
      [](cppCLASS &self, const std::optional<std::vector<transport::MultiplicitySum>> &value)
      {
         self.multiplicitySum() = value;
      },
      cppCLASS::component_t::documentation("multiplicity_sum").data()
   );

   // add standard definitions
   addStandardComponentDefinitions<cppCLASS>(object);
}

} // namespace python_transport
} // namespace python_v2_0
