
// THIS FILE WAS AUTOGENERATED!
// DO NOT MODIFY!

#ifndef TEST_V2_0_RESONANCES_UNRESOLVED
#define TEST_V2_0_RESONANCES_UNRESOLVED

#include "test/v2.0/resonances/TabulatedWidths.hpp"

namespace test {
namespace v2_0 {
namespace resonances {

// -----------------------------------------------------------------------------
// resonances::
// class Unresolved
// -----------------------------------------------------------------------------

class Unresolved :
   public Component<resonances::Unresolved>
{
   friend class Component;

   using _t = std::variant<
      resonances::TabulatedWidths
   >;

   // ------------------------
   // For Component
   // ------------------------

   // Names: this namespace and class, and original nodes (as in XML <...>)
   static auto NAMESPACE() { return "resonances"; }
   static auto CLASS() { return "Unresolved"; }
   static auto NODENAME() { return "unresolved"; }

   // Core Interface multi-query to transfer information to/from core Nodes
   static auto KEYS()
   {
      return
         // comment
         ++Child<std::string>(special::comment) / CommentConverter{} |

         // metadata
         Float64{}
            / Meta<>("domainMin") |
         Float64{}
            / Meta<>("domainMax") |
         XMLName{}
            / Meta<>("domainUnit") |

         // children
         _t{}
            / --(Child<>("tabulatedWidths"))
      ;
   }

   // Data member names. Usually - but not necessarily - the same as the node
   // names appearing in KEYS(). These are used by Component's prettyprinter.
   static const auto &FIELDNAMES()
   {
      static const std::vector<std::string> names = {
         "comment",
         "domainMin",
         "domainMax",
         "domainUnit",
         "_tabulatedWidths"
      };
      return names;
   }

   // Data member names, as they'll be presented in the Python bindings.
   static const auto &PYTHONNAMES()
   {
      static const std::vector<std::string> names = {
         "comment",
         "domain_min",
         "domain_max",
         "domain_unit",
         "_tabulated_widths"
      };
      return names;
   }

   // ------------------------
   // Public interface
   // ------------------------

public:

   using component_t = Component;
   using Component::construct;

   // ------------------------
   // Data members
   // ------------------------

   // comment
   Field<std::vector<std::string>> comment{this};

   // metadata
   Field<Float64>
      domainMin{this};
   Field<Float64>
      domainMax{this};
   Field<XMLName>
      domainUnit{this};

   // children - variant
   Field<_t>
      _tabulatedWidths{this};
   FieldPart<decltype(_tabulatedWidths),resonances::TabulatedWidths> tabulatedWidths{_tabulatedWidths};

   // ------------------------
   // Constructors
   // ------------------------

   #define GNDSTK_COMPONENT(blockdata) \
   Component( \
      blockdata, \
      this->comment, \
      this->domainMin, \
      this->domainMax, \
      this->domainUnit, \
      this->_tabulatedWidths \
   )

   // default
   Unresolved() :
      GNDSTK_COMPONENT(BlockData{})
   {
      Component::finish();
   }

   // from fields, comment excluded
   explicit Unresolved(
      const wrapper<Float64>
         &domainMin,
      const wrapper<Float64>
         &domainMax = {},
      const wrapper<XMLName>
         &domainUnit = {},
      const wrapper<_t>
         &_tabulatedWidths = {}
   ) :
      GNDSTK_COMPONENT(BlockData{}),
      domainMin(this,domainMin),
      domainMax(this,domainMax),
      domainUnit(this,domainUnit),
      _tabulatedWidths(this,_tabulatedWidths)
   {
      Component::finish();
   }

   // from node
   explicit Unresolved(const Node &node) :
      GNDSTK_COMPONENT(BlockData{})
   {
      Component::finish(node);
   }

   // copy
   Unresolved(const Unresolved &other) :
      GNDSTK_COMPONENT(other.baseBlockData()),
      comment(this,other.comment),
      domainMin(this,other.domainMin),
      domainMax(this,other.domainMax),
      domainUnit(this,other.domainUnit),
      _tabulatedWidths(this,other._tabulatedWidths)
   {
      Component::finish(other);
   }

   // move
   Unresolved(Unresolved &&other) :
      GNDSTK_COMPONENT(other.baseBlockData()),
      comment(this,std::move(other.comment)),
      domainMin(this,std::move(other.domainMin)),
      domainMax(this,std::move(other.domainMax)),
      domainUnit(this,std::move(other.domainUnit)),
      _tabulatedWidths(this,std::move(other._tabulatedWidths))
   {
      Component::finish(other);
   }

   // ------------------------
   // Assignment operators
   // ------------------------

   // copy
   Unresolved &operator=(const Unresolved &other)
   {
      if (this != &other) {
         Component::operator=(other);
         comment = other.comment;
         domainMin = other.domainMin;
         domainMax = other.domainMax;
         domainUnit = other.domainUnit;
         _tabulatedWidths = other._tabulatedWidths;
      }
      return *this;
   }

   // move
   Unresolved &operator=(Unresolved &&other)
   {
      if (this != &other) {
         Component::operator=(std::move(other));
         comment = std::move(other.comment);
         domainMin = std::move(other.domainMin);
         domainMax = std::move(other.domainMax);
         domainUnit = std::move(other.domainUnit);
         _tabulatedWidths = std::move(other._tabulatedWidths);
      }
      return *this;
   }

   // ------------------------
   // Custom functionality
   // ------------------------

   #include "test/v2.0/resonances/Unresolved/src/custom.hpp"
   #undef GNDSTK_COMPONENT
}; // class Unresolved

} // namespace resonances
} // namespace v2_0
} // namespace test

#endif
