
// THIS FILE WAS AUTOGENERATED!
// DO NOT MODIFY!

// system includes
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

// local includes
#include "alpha/v2.0/general/ResonanceReactions.hpp"
#include "definitions.hpp"

// namespace aliases
namespace python = pybind11;

namespace python_v2_0 {
namespace python_general {

// ResonanceReactions wrapper
void wrapResonanceReactions(python::module &module)
{
   using namespace alpha;
   using namespace alpha::v2_0;

   // type aliases
   using Component = general::ResonanceReactions;

   // create the component
   python::class_<Component> component(
      module, "ResonanceReactions",
      Component::documentation().data()
   );

   // wrap the component
   component
      .def(
         python::init<
            const std::vector<general::ResonanceReaction> &
         >(),
         python::arg("resonance_reaction"),
         Component::documentation("constructor").data()
      )
      .def_property_readonly(
         "resonance_reaction",
         [](const Component &self)
         {
            return self.resonanceReaction();
         },
         Component::documentation("resonance_reaction").data()
      )
   ;

   // add standard component definitions
   addStandardComponentDefinitions<Component>(component);
}

} // namespace python_general
} // namespace python_v2_0
