
// THIS FILE WAS AUTOGENERATED!
// DO NOT MODIFY!

// system includes
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

// local includes
#include "alpha/v2.0/general/Spectra.hpp"
#include "definitions.hpp"

// namespace aliases
namespace python = pybind11;

namespace python_v2_0 {
namespace python_general {

// Spectra wrapper
void wrapSpectra(python::module &module)
{
   using namespace alpha;
   using namespace alpha::v2_0;

   // type aliases
   using Component = general::Spectra;

   // create the component
   python::class_<Component> component(
      module, "Spectra",
      Component::documentation().data()
   );

   // wrap the component
   component
      .def(
         python::init<
            const std::vector<general::Spectrum> &
         >(),
         python::arg("spectrum"),
         Component::documentation("constructor").data()
      )
      .def_property_readonly(
         "spectrum",
         [](const Component &self)
         {
            return self.spectrum();
         },
         Component::documentation("spectrum").data()
      )
   ;

   // add standard component definitions
   addStandardComponentDefinitions<Component>(component);
}

} // namespace python_general
} // namespace python_v2_0
