
// THIS FILE WAS AUTOGENERATED!
// DO NOT MODIFY!

#ifndef GNDS_V2_0_GENERAL_XYS1D
#define GNDS_V2_0_GENERAL_XYS1D

#include "GNDS/v2.0/general/Axes.hpp"
#include "GNDS/v2.0/general/Values.hpp"
#include "GNDS/v2.0/general/Uncertainty.hpp"

namespace GNDS {
namespace v2_0 {
namespace general {

// -----------------------------------------------------------------------------
// general::
// class XYs1d
// -----------------------------------------------------------------------------

class XYs1d :
   public Component<general::XYs1d>
{
   friend class Component;

   // ------------------------
   // For Component
   // ------------------------

   // Names: this namespace and class, and original nodes (as in XML <...>)
   static auto NAMESPACE() { return "general"; }
   static auto CLASS() { return "XYs1d"; }
   static auto NODENAME() { return "XYs1d"; }

   // Core Interface multi-query to transfer information to/from core Nodes
   static auto KEYS()
   {
      return
         // comment
         ++Child<std::string>(special::comment) / CommentConverter{} |

         // metadata
         std::optional<std::string>{}
            / Meta<>("label") |
         std::optional<int>{}
            / Meta<>("index") |
         std::optional<std::string>{}
            / Meta<>("interpolation") |
         std::optional<double>{}
            / Meta<>("outerDomainValue") |

         // children
         --Child<std::optional<general::Axes>>
            ("axes") |
         --Child<general::Values>
            ("values") |
         --Child<std::optional<general::Uncertainty>>
            ("uncertainty")
      ;
   }

   // Data member names. Usually - but not necessarily - the same as the node
   // names appearing in KEYS(). These are used by Component's prettyprinter.
   static const auto &FIELDNAMES()
   {
      static const std::vector<std::string> names = {
         "comment",
         "label",
         "index",
         "interpolation",
         "outerDomainValue",
         "axes",
         "values",
         "uncertainty"
      };
      return names;
   }

   // Data member names, as they'll be presented in the Python bindings.
   static const auto &PYTHONNAMES()
   {
      static const std::vector<std::string> names = {
         "comment",
         "label",
         "index",
         "interpolation",
         "outer_domain_value",
         "axes",
         "values",
         "uncertainty"
      };
      return names;
   }

   // ------------------------
   // Public interface
   // ------------------------

public:

   using component_t = Component;
   using Component::construct;

   // ------------------------
   // Data members
   // ------------------------

   // comment
   Field<std::vector<std::string>> comment{this};

   // metadata
   Field<std::optional<std::string>>
      label{this};
   Field<std::optional<int>>
      index{this};
   Field<std::optional<std::string>>
      interpolation{this};
   Field<std::optional<double>>
      outerDomainValue{this};

   // children
   Field<std::optional<general::Axes>>
      axes{this};
   Field<general::Values>
      values{this};
   Field<std::optional<general::Uncertainty>>
      uncertainty{this};

   // ------------------------
   // Constructors
   // ------------------------

   #define NJOY_GNDSTK_COMPONENT(blockdata) \
   Component( \
      blockdata, \
      this->comment, \
      this->label, \
      this->index, \
      this->interpolation, \
      this->outerDomainValue, \
      this->axes, \
      this->values, \
      this->uncertainty \
   )

   // default
   XYs1d() :
      NJOY_GNDSTK_COMPONENT(BlockData{})
   {
      Component::finish();
   }

   // from fields, comment excluded
   explicit XYs1d(
      const wrapper<std::optional<std::string>>
         &label,
      const wrapper<std::optional<int>>
         &index = {},
      const wrapper<std::optional<std::string>>
         &interpolation = {},
      const wrapper<std::optional<double>>
         &outerDomainValue = {},
      const wrapper<std::optional<general::Axes>>
         &axes = {},
      const wrapper<general::Values>
         &values = {},
      const wrapper<std::optional<general::Uncertainty>>
         &uncertainty = {}
   ) :
      NJOY_GNDSTK_COMPONENT(BlockData{}),
      label(this,label),
      index(this,index),
      interpolation(this,interpolation),
      outerDomainValue(this,outerDomainValue),
      axes(this,axes),
      values(this,values),
      uncertainty(this,uncertainty)
   {
      Component::finish();
   }

   // from node
   explicit XYs1d(const Node &node) :
      NJOY_GNDSTK_COMPONENT(BlockData{})
   {
      Component::finish(node);
   }

   // copy
   XYs1d(const XYs1d &other) :
      NJOY_GNDSTK_COMPONENT(other.baseBlockData()),
      comment(this,other.comment),
      label(this,other.label),
      index(this,other.index),
      interpolation(this,other.interpolation),
      outerDomainValue(this,other.outerDomainValue),
      axes(this,other.axes),
      values(this,other.values),
      uncertainty(this,other.uncertainty)
   {
      Component::finish(other);
   }

   // move
   XYs1d(XYs1d &&other) :
      NJOY_GNDSTK_COMPONENT(other.baseBlockData()),
      comment(this,std::move(other.comment)),
      label(this,std::move(other.label)),
      index(this,std::move(other.index)),
      interpolation(this,std::move(other.interpolation)),
      outerDomainValue(this,std::move(other.outerDomainValue)),
      axes(this,std::move(other.axes)),
      values(this,std::move(other.values)),
      uncertainty(this,std::move(other.uncertainty))
   {
      Component::finish(other);
   }

   // ------------------------
   // Assignment operators
   // ------------------------

   // copy
   XYs1d &operator=(const XYs1d &other)
   {
      if (this != &other) {
         Component::operator=(other);
         comment = other.comment;
         label = other.label;
         index = other.index;
         interpolation = other.interpolation;
         outerDomainValue = other.outerDomainValue;
         axes = other.axes;
         values = other.values;
         uncertainty = other.uncertainty;
      }
      return *this;
   }

   // move
   XYs1d &operator=(XYs1d &&other)
   {
      if (this != &other) {
         Component::operator=(std::move(other));
         comment = std::move(other.comment);
         label = std::move(other.label);
         index = std::move(other.index);
         interpolation = std::move(other.interpolation);
         outerDomainValue = std::move(other.outerDomainValue);
         axes = std::move(other.axes);
         values = std::move(other.values);
         uncertainty = std::move(other.uncertainty);
      }
      return *this;
   }

   // ------------------------
   // Custom functionality
   // ------------------------

   #include "GNDS/v2.0/general/XYs1d/src/custom.hpp"
   #undef NJOY_GNDSTK_COMPONENT
}; // class XYs1d

} // namespace general
} // namespace v2_0
} // namespace GNDS

#endif
