
// THIS FILE WAS AUTOGENERATED!
// DO NOT MODIFY!

// system includes
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

// local includes
#include "try/v2.0/processed/AngularEnergyMC.hpp"
#include "definitions.hpp"

// namespace aliases
namespace python = pybind11;

namespace python_v2_0 {
namespace python_processed {

// AngularEnergyMC wrapper
void wrapAngularEnergyMC(python::module &module)
{
   using namespace try;
   using namespace try::v2_0;

   // type aliases
   using Component = processed::AngularEnergyMC;

   // create the component
   python::class_<Component> component(
      module,
      "AngularEnergyMC",
      Component::documentation().data()
   );

   // wrap the component
   component
      .def(
         python::init<
            const XMLName &,
            const XMLName &,
            const transport::Angular_uncorrelated &,
            const transport::AngularEnergy &
         >(),
         python::arg("label"),
         python::arg("product_frame"),
         python::arg("angular"),
         python::arg("angular_energy"),
         Component::documentation("constructor").data()
      )
      .def_property_readonly(
         "label",
         [](const Component &self) { return self.label(); },
         Component::documentation("label").data()
      )
      .def_property_readonly(
         "product_frame",
         [](const Component &self) { return self.productFrame(); },
         Component::documentation("product_frame").data()
      )
      .def_property_readonly(
         "angular",
         [](const Component &self) { return self.angular(); },
         Component::documentation("angular").data()
      )
      .def_property_readonly(
         "angular_energy",
         [](const Component &self) { return self.angularEnergy(); },
         Component::documentation("angular_energy").data()
      )
   ;

   // add standard component definitions
   addStandardComponentDefinitions< Component >( component );
}

} // namespace python_processed
} // namespace python_v2_0
