#!/bin/bash

COMPILE="
   clang++ -std=c++17
  -DGNDSTK_HACK
  -IGNDStk/src
  -IIncidentNeutron/src
  -Ideps/pugixml-adapter-src/src/src
  -Ideps/hdf5-src/include
  -Ideps/json-src/include
  -Ideps/json-src/include/nlohmann
  -Ideps/log-src/src
  -Ideps/spdlog-src/include
  -I/usr/include/hdf5/serial
  -DHIGHFIVE_USE_BOOST=OFF
  -L/usr/lib/x86_64-linux-gnu/hdf5/serial
  -lhdf5
  -fno-show-column
  -Wno-unused-command-line-argument
  -Wall -Wextra -Wpedantic "
# -g -O3

if [ ! -f "pugixml.o" ]; then
echo 'Compiling pugixml.cpp...'
$COMPILE \
   deps/pugixml-adapter-src/src/src/pugixml.cpp \
  -c -o pugixml.o
fi

# Compile examples
echo 'Compiling...'
$COMPILE 1.cpp pugixml.o -o 1
