#!/bin/bash

# Simple compilation command for the example codes in this directory.
# We assume here that GNDStk points to the base GNDStk/ directory of
# the repo, and that deps points to GNDStk/build/_deps/. (Which also
# means essentially that you should build GNDStk's test suite first.)
# You may need tweaks below, e.g. to /usr... stuff.
COMPILE="
   clang++ -std=c++17
  -IGNDStk/src
  -IGNDStk/simple-json/src
  -Ignds/src
  -Ideps/pugixml-adapter-src/src/src
  -Ideps/hdf5-src/include
  -Ideps/log-src/src
  -Ideps/spdlog-src/include
  -I/usr/include/hdf5/serial
  -DHIGHFIVE_USE_BOOST=OFF
  -L/usr/lib/x86_64-linux-gnu/hdf5/serial
  -lhdf5
  -fno-show-column
  -Wno-unused-command-line-argument
  -Wall -Wextra -Wpedantic "

# If the compiler and/or flags are changed, consider deleting pugixml.o
# so that it gets compiled again, given this conditional...
if [ ! -f "pugixml.o" ]; then
   echo 'Compiling pugixml.cpp...'
   $COMPILE deps/pugixml-adapter-src/src/src/pugixml.cpp -c -o pugixml.o
fi

# Compile examples
echo 'Compiling the examples...'
$COMPILE 1.cpp pugixml.o -o 1 &
$COMPILE 2.cpp pugixml.o -o 2 &
wait $(jobs -p)
