
// THIS FILE WAS AUTOGENERATED!
// DO NOT MODIFY!

#ifndef TEST_V2_0_DOCUMENTATION_AFFILIATIONS
#define TEST_V2_0_DOCUMENTATION_AFFILIATIONS

#include "test/v2.0/documentation/Affiliation.hpp"

namespace test {
namespace v2_0 {
namespace documentation {

// -----------------------------------------------------------------------------
// documentation::
// class Affiliations
// -----------------------------------------------------------------------------

class Affiliations : public Component<documentation::Affiliations> {
   friend class Component;

   // ------------------------
   // For Component
   // ------------------------

   // Names: this namespace, this class, a field/node of this type
   static auto NAMESPACE() { return "documentation"; }
   static auto CLASS() { return "Affiliations"; }
   static auto FIELD() { return "affiliations"; }

   // Core Interface multi-query to extract metadata and child nodes
   static auto KEYS()
   {
      return
         // children
         ++Child<documentation::Affiliation>("affiliation")
      ;
   }

public:
   using Component::construct;

   // children
   Field<std::vector<documentation::Affiliation>> affiliation{this};

   // ------------------------
   // Constructors
   // ------------------------

   #define GNDSTK_COMPONENT(blockdata) Component(blockdata, \
      this->affiliation)

   // default
   Affiliations() :
      GNDSTK_COMPONENT(BlockData{})
   {
      Component::finish();
   }

   // from fields
   explicit Affiliations(
      const wrapper<std::vector<documentation::Affiliation>> &affiliation
   ) :
      GNDSTK_COMPONENT(BlockData{}),
      affiliation(this,affiliation)
   {
      Component::finish();
   }

   // from node
   explicit Affiliations(const Node &node) :
      GNDSTK_COMPONENT(BlockData{})
   {
      Component::finish(node);
   }

   // copy
   Affiliations(const Affiliations &other) :
      GNDSTK_COMPONENT(other.baseBlockData()),
      affiliation(this,other.affiliation)
   {
      Component::finish(other);
   }

   // move
   Affiliations(Affiliations &&other) :
      GNDSTK_COMPONENT(other.baseBlockData()),
      affiliation(this,std::move(other.affiliation))
   {
      Component::finish(other);
   }

   // ------------------------
   // Assignment operators
   // ------------------------

   Affiliations &operator=(const Affiliations &) = default;
   Affiliations &operator=(Affiliations &&) = default;

   // ------------------------
   // Custom functionality
   // ------------------------

   #include "test/v2.0/documentation/Affiliations/src/custom.hpp"
   #undef GNDSTK_COMPONENT
}; // class Affiliations

} // namespace documentation
} // namespace v2_0
} // namespace test

#endif
