
// THIS FILE WAS AUTOGENERATED!
// DO NOT MODIFY!

#ifndef TEST_V2_0_TRANSPORT_UNCORRELATED
#define TEST_V2_0_TRANSPORT_UNCORRELATED

#include "test/v2.0/transport/Angular_uncorrelated.hpp"
#include "test/v2.0/transport/Energy_uncorrelated.hpp"

namespace test {
namespace v2_0 {
namespace transport {

// -----------------------------------------------------------------------------
// transport::
// class Uncorrelated
// -----------------------------------------------------------------------------

class Uncorrelated :
   public Component<transport::Uncorrelated>
{
   friend class Component;

   // ------------------------
   // For Component
   // ------------------------

   // Names: this namespace, this class, and a field/node of this type
   static auto NAMESPACE() { return "transport"; }
   static auto CLASS() { return "Uncorrelated"; }
   static auto FIELD() { return "uncorrelated"; }

   // Core Interface multi-query to transfer information to/from Nodes
   static auto KEYS()
   {
      return
         // comment
         ++Child<std::string>(special::comment) / CommentConverter{} |

         // metadata
         std::optional<XMLName>{}
            / Meta<>("label") |
         XMLName{}
            / Meta<>("productFrame") |

         // children
         --Child<transport::Angular_uncorrelated>("angular") |
         --Child<transport::Energy_uncorrelated>("energy")
      ;
   }

public:
   using Component::construct;

   // comment
   Field<std::vector<std::string>> comment{this};

   // metadata
   Field<std::optional<XMLName>> label{this};
   Field<XMLName> productFrame{this};

   // children
   Field<transport::Angular_uncorrelated> angular_uncorrelated{this};
   Field<transport::Energy_uncorrelated> energy_uncorrelated{this};

   // ------------------------
   // Constructors
   // ------------------------

   #define GNDSTK_COMPONENT(blockdata) Component(blockdata, \
      this->comment, \
      this->label, \
      this->productFrame, \
      this->angular_uncorrelated, \
      this->energy_uncorrelated)

   // default
   Uncorrelated() :
      GNDSTK_COMPONENT(BlockData{})
   {
      Component::finish();
   }

   // from fields, comment excluded
   explicit Uncorrelated(
      const wrapper<std::optional<XMLName>> &label,
      const wrapper<XMLName> &productFrame = {},
      const wrapper<transport::Angular_uncorrelated> &angular_uncorrelated = {},
      const wrapper<transport::Energy_uncorrelated> &energy_uncorrelated = {}
   ) :
      GNDSTK_COMPONENT(BlockData{}),
      label(this,label),
      productFrame(this,productFrame),
      angular_uncorrelated(this,angular_uncorrelated),
      energy_uncorrelated(this,energy_uncorrelated)
   {
      Component::finish();
   }

   // from node
   explicit Uncorrelated(const Node &node) :
      GNDSTK_COMPONENT(BlockData{})
   {
      Component::finish(node);
   }

   // copy
   Uncorrelated(const Uncorrelated &other) :
      GNDSTK_COMPONENT(other.baseBlockData()),
      comment(this,other.comment),
      label(this,other.label),
      productFrame(this,other.productFrame),
      angular_uncorrelated(this,other.angular_uncorrelated),
      energy_uncorrelated(this,other.energy_uncorrelated)
   {
      Component::finish(other);
   }

   // move
   Uncorrelated(Uncorrelated &&other) :
      GNDSTK_COMPONENT(other.baseBlockData()),
      comment(this,std::move(other.comment)),
      label(this,std::move(other.label)),
      productFrame(this,std::move(other.productFrame)),
      angular_uncorrelated(this,std::move(other.angular_uncorrelated)),
      energy_uncorrelated(this,std::move(other.energy_uncorrelated))
   {
      Component::finish(other);
   }

   // ------------------------
   // Assignment operators
   // ------------------------

   Uncorrelated &operator=(const Uncorrelated &) = default;
   Uncorrelated &operator=(Uncorrelated &&) = default;

   // ------------------------
   // Custom functionality
   // ------------------------

   #include "test/v2.0/transport/Uncorrelated/src/custom.hpp"
   #undef GNDSTK_COMPONENT
}; // class Uncorrelated

} // namespace transport
} // namespace v2_0
} // namespace test

#endif
