#!/bin/bash

# C++ compilation command
COMPILE="
   clang++ -std=c++17
  -I../../../GNDStk/src  -I../../../GNDStk/c/src
  -Imulti/src         -Imulti/c/src
  -I../../../GNDStk/build/_deps/pugixml-adapter-src/src/src
  -I../../../GNDStk/build/_deps/hdf5-src/include
  -I../../../GNDStk/build/_deps/json-src/include
  -I../../../GNDStk/build/_deps/json-src/include/nlohmann
  -I../../../GNDStk/build/_deps/log-src/src
  -I../../../GNDStk/build/_deps/spdlog-src/include
  -I/usr/include/hdf5/serial
  -DHIGHFIVE_USE_BOOST=OFF
  -L/usr/lib/x86_64-linux-gnu/hdf5/serial
  -lhdf5
  -fno-show-column
  -Wno-unused-command-line-argument
  -Wall -Wextra -Wpedantic "

# pugixml
if [ ! -f "pugixml.o" ]; then
$COMPILE ../../../GNDStk/build/_deps/pugixml-adapter-src/src/src/pugixml.cpp -c
fi

# Compile C++
$COMPILE -c ../../../GNDStk/c/src/GNDStk.cpp
$COMPILE -c multi/c/src/v1/multigroup/Foobar.cpp
$COMPILE -c multi/c/src/v1/multigroup/Isotope.cpp
$COMPILE -c multi/c/src/v1/multigroup/Element.cpp

# Compile C
clang \
  -I../../../GNDStk/c/src \
  -Imulti/c/src \
   example.c \
   pugixml.o GNDStk.o Foobar.o Isotope.o Element.o \
  -L/usr/lib/x86_64-linux-gnu/hdf5/serial \
  -lstdc++ -lm -lhdf5 \
  -o c.exe
