
// THIS FILE WAS AUTOGENERATED!
// DO NOT MODIFY!

#include "alpha/v2.0/general/Styles.hpp"
#include "Styles.h"

using namespace njoy::GNDStk;
using namespace alpha::v2_0;

using C = StylesClass;
using CPP = multigroup::Styles;

static const std::string CLASSNAME = "Styles";

namespace extract {
   static auto evaluated = [](auto &obj) { return &obj.evaluated; };
   static auto crossSectionReconstructed = [](auto &obj) { return &obj.crossSectionReconstructed; };
}

using CPPEvaluated = general::Evaluated;
using CPPCrossSectionReconstructed = general::CrossSectionReconstructed;


// -----------------------------------------------------------------------------
// Basics
// Create, Assign, Delete
// -----------------------------------------------------------------------------

// Create, default, const
Handle2ConstStyles
StylesDefaultConst()
{
   return detail::createHandle<CPP,C>
      (CLASSNAME, CLASSNAME+"DefaultConst");
}

// Create, default
Handle2Styles
StylesDefault()
{
   return detail::createHandle<CPP,C>
      (CLASSNAME, CLASSNAME+"Default");
}

// Create, general, const
Handle2ConstStyles
StylesCreateConst(
   ConstHandle2ConstEvaluated evaluated,
   ConstHandle2ConstCrossSectionReconstructed crossSectionReconstructed
) {
   ConstHandle2Styles handle = detail::createHandle<CPP,C>(
      CLASSNAME, CLASSNAME+"CreateConst",
      detail::tocpp<CPPEvaluated>(evaluated),
      detail::tocpp<CPPCrossSectionReconstructed>(crossSectionReconstructed)
   );
   return handle;
}

// Create, general
Handle2Styles
StylesCreate(
   ConstHandle2ConstEvaluated evaluated,
   ConstHandle2ConstCrossSectionReconstructed crossSectionReconstructed
) {
   ConstHandle2Styles handle = detail::createHandle<CPP,C>(
      CLASSNAME, CLASSNAME+"Create",
      detail::tocpp<CPPEvaluated>(evaluated),
      detail::tocpp<CPPCrossSectionReconstructed>(crossSectionReconstructed)
   );
   return handle;
}

// Assign
// Use this to assign one handled object to another. Don't assign handles,
// as with to = from. That has a meaning that you probably don't intend.
void
StylesAssign(ConstHandle2Styles self, ConstHandle2ConstStyles from)
{
   detail::assignHandle<CPP,C>
      (CLASSNAME, CLASSNAME+"Assign", self, from);
}

// Delete
// We'll attempt to remove no-longer-used objects automatically, but you
// may improve performance if you delete them when you're done with them.
void
StylesDelete(ConstHandle2ConstStyles self)
{
   detail::deleteHandle<CPP,C>
      (CLASSNAME, CLASSNAME+"Delete", self);
}


// -----------------------------------------------------------------------------
// I/O
// Read, Write, Print
// Each returns 0 if failure, 1 if success.
// -----------------------------------------------------------------------------

// Read from file
// File can be XML, JSON, or HDF5.
// We'll examine the file's contents to determine its type automatically.
int
StylesRead(ConstHandle2Styles self, const char *const filename)
{
   return detail::readHandle<CPP,C>
      (CLASSNAME, CLASSNAME+"Read", self, filename);
}

// Write to file
// File can be XML, JSON, or HDF5.
// We'll use filename's extension to determine the type you want written.
int
StylesWrite(ConstHandle2ConstStyles self, const char *const filename)
{
   return detail::writeHandle<CPP,C>
      (CLASSNAME, CLASSNAME+"Write", self, filename);
}

// Print to standard output, in our prettyprinting format
int
StylesPrint(ConstHandle2ConstStyles self)
{
   return detail::printHandle<CPP,C>
      (CLASSNAME, CLASSNAME+"Print", self);
}

// Print to standard output, as XML
int
StylesPrintXML(ConstHandle2ConstStyles self)
{
   return detail::printHandle<CPP,C>
      (CLASSNAME, CLASSNAME+"PrintXML", self, "XML");
}

// Print to standard output, as JSON
int
StylesPrintJSON(ConstHandle2ConstStyles self)
{
   return detail::printHandle<CPP,C>
      (CLASSNAME, CLASSNAME+"PrintJSON", self, "JSON");
}


// -----------------------------------------------------------------------------
// Child: evaluated
// -----------------------------------------------------------------------------

// Has
int
StylesEvaluatedHas(ConstHandle2ConstStyles self)
{
   return detail::hasField<CPP>
      (CLASSNAME, CLASSNAME+"EvaluatedHas", self, extract::evaluated);
}

// Get, const
Handle2ConstEvaluated
StylesEvaluatedGetConst(ConstHandle2ConstStyles self)
{
   return detail::getField<CPP,Handle2ConstEvaluated>
      (CLASSNAME, CLASSNAME+"EvaluatedGetConst", self, extract::evaluated);
}

// Get, non-const
Handle2Evaluated
StylesEvaluatedGet(ConstHandle2Styles self)
{
   return detail::getField<CPP,Handle2Evaluated>
      (CLASSNAME, CLASSNAME+"EvaluatedGet", self, extract::evaluated);
}

// Set
void
StylesEvaluatedSet(ConstHandle2Styles self, ConstHandle2ConstEvaluated evaluated)
{
   detail::setField<CPP,CPPEvaluated>
      (CLASSNAME, CLASSNAME+"EvaluatedSet", self, extract::evaluated, evaluated);
}


// -----------------------------------------------------------------------------
// Child: crossSectionReconstructed
// -----------------------------------------------------------------------------

// Has
int
StylesCrossSectionReconstructedHas(ConstHandle2ConstStyles self)
{
   return detail::hasField<CPP>
      (CLASSNAME, CLASSNAME+"CrossSectionReconstructedHas", self, extract::crossSectionReconstructed);
}

// Get, const
Handle2ConstCrossSectionReconstructed
StylesCrossSectionReconstructedGetConst(ConstHandle2ConstStyles self)
{
   return detail::getField<CPP,Handle2ConstCrossSectionReconstructed>
      (CLASSNAME, CLASSNAME+"CrossSectionReconstructedGetConst", self, extract::crossSectionReconstructed);
}

// Get, non-const
Handle2CrossSectionReconstructed
StylesCrossSectionReconstructedGet(ConstHandle2Styles self)
{
   return detail::getField<CPP,Handle2CrossSectionReconstructed>
      (CLASSNAME, CLASSNAME+"CrossSectionReconstructedGet", self, extract::crossSectionReconstructed);
}

// Set
void
StylesCrossSectionReconstructedSet(ConstHandle2Styles self, ConstHandle2ConstCrossSectionReconstructed crossSectionReconstructed)
{
   detail::setField<CPP,CPPCrossSectionReconstructed>
      (CLASSNAME, CLASSNAME+"CrossSectionReconstructedSet", self, extract::crossSectionReconstructed, crossSectionReconstructed);
}


// -----------------------------------------------------------------------------
// Custom functionality
// -----------------------------------------------------------------------------

#include "v2.0/general/Styles/src/custom.cpp"
